### ISSUE TITLE
research the details around FTP Ramp test calculations

### ISSUE THREAD

**Issue by dvmarinoff** [dvmarinoff/Flux#75]
- interval length (30 s, 60s, 120s, etc.)
- what percentage of final interval power
- how time covered in the last interval relates to the final calculation

**Comment by loopingleo** [comment]
Hi @dvmarinoff -
what do you mean by research? Are you looking for standard percentages?
I can tell from Zwift that there you can do a ramp test with 60s steps going up 20W every step.
Then you take 75% percent of your last step completed plus seconds elapsed in incomplete step divided by 60 times 20W and add this part to the previous value. 
It is a very simple calculation.
Let me know if you meant this or had a different question in mind.

**Comment by dvmarinoff** [comment]
Yeah, something like that, but when you start digging in all the discussion around the various forums (TR, slowtwitch, etc.) cycling coaching podcasts and so on, there seems to be an infinite amount of details and many claims about this test measuring way better than some other test that kinda looks almost identical. And going down this rabbit hole you soon find yourself reading academic papers, and meta discussions debating the scientific validity of the results of those papers, and ..

One of the first debates is should it be 20W or 5% or 6% or maybe an FTP adjusted value.
And I also remember GPLama had this [video](https://youtu.be/ZtKTdf9yhZE) some time ago, it has all needed, but I should at least ask for permission to use ...

**Comment by loopingleo** [comment]
I agree. There is a lot of research and various opinions on what is the best testing protocol. 
However, I think it is always going to be just another estimate. Results vary from person to person. Especially, if you are training a specific area of your power profile. For instance, one of my cycling strengths is a pretty high maximum aerobic power (~5 min power). In my case, at the end of this road racing season, doing a ramp test resulted in a significant overestimation my FTP. Simply because I am very strong in these last 5 minutes of the ramp. Hence, my FTP was estimated to be 328W whereas my highest ever 20 min power is below 300W. 
I conclude there is no perfect testing protocol. Ideally, you should decide what part of your power profile has the highest importance to you. And then do critical power tests for that particular time period. 
What do you think?

**Comment by dvmarinoff** [comment]
I am not a coach or anything, but I agree. The real picture can be more complex than what the 20 min and the Ramp test could show. Moreover while the former is really hard to pace and prone to underestimation, the later for some riders can result in significant overestimation. Yet doing the 1 hour test each month is really taxing.

Anyway the Ramp tests seem to be the norm now and it's going to be a requested feature.

**Comment by dvmarinoff** [comment]
Ramp Tests:


```
TR:
warmup: 46%
block_1: 52%
block_2: 58%
block_n: block_n-1 + 6%
```


```
Zwift:
warmup: Free Ride
block_1: 100W
block_2: 120W
block_n: block_n-1 + 20W
```
![Screenshot 2021-12-15 at 11 21 57](https://user-images.githubusercontent.com/7523832/146181045-f72b9ec0-a3ae-4a27-a2c5-c7fd0014be39.png)

Source: SMART Bike Trainers  on [YouTube ](https://www.youtube.com/watch?v=QPWe8JxkxwE&t=277s)
