### ISSUE TITLE
db / storage: power and heart rate history during ride

### ISSUE THREAD

**Issue by loopingleo** [dvmarinoff/Flux#83]
Hi @dvmarinoff 
How can I access power and heart rate history data during the rate?
For instance, last 30 sec HR average etc.
Thanks!

**Comment by dvmarinoff** [comment]
In db you will find:
  -  `elapsed: <int>`,
Which is the number of running seconds since the timer has been started:

```
let elapsed;
xf.sub(‘db:elapsed’, function(value) {
    elapsed = value;
});

let heartRate;
xf.sub(‘db:heartRate’, function(value) {
    heartRate = value;
});
```

I guess you can calculate locally avg value over some period by using those two.
You can also use as an example the [PowerAvg view](https://github.com/dvmarinoff/Flux/blob/e0fddabb9b2a48ee4031036425017c1f2930ca8c/src/views/data-views.js#L223) which calculates average lap power.

And all relevant records are stored in the `db.records` array, which is persisted in IDB storage. You can sub for it and take the last 30 records or something like that. The structure of the record object is the following:

<img width="563" alt="Screenshot 2021-12-20 at 23 25 45" src="https://user-images.githubusercontent.com/7523832/146835088-2dced6c9-f61e-45e5-9013-3e18ba7a822d.png">

Hope you can do something with that,
Cheers!
